#!/bin/sh

# Test driver for CRSX java backend.

function show_help {
    echo "Usage : $0 help"
    echo "        $0 <input.crs>"
}

function test {
    if [ $# -lt 1 ]     
    then
        show_help
        exit 0
    fi
        
    # Parse arguments
    local input=
    while :
    do
        case $1 in
            help)
                show_help
                exit 0
                ;;
            -*)
                printf >&2 "warning: unknown option: %s\n" "$1"
                shift
                ;;
             *) 
                break
                ;;    
        esac
    done
    
    if [ "$1" = "" ]
    then
       echo "Missing file name"
       exit
    fi
    
    if [ ! -f $1 ]
    then
        echo "Filename given \"$1\" doesn't exist"
        exit
    fi
       
}

test